<?php

namespace App\Models;

use App\Scopes\OrganizerUserScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organizer extends User
{
    use HasFactory;

    protected $table = 'users';

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new OrganizerUserScope);
    }

    public function events()
    {
        return $this->hasMany(Event::class, 'user_id');
    }
}
